"""
End Screen Builder — FastPath Version
Generates the final user-facing message using the clarity noun.
"""

def build_end_screen(data: dict) -> str:
    """
    Build the final end screen message using the clarity noun
    generated by the NamingEngine.
    """

    clarity_noun = data.get("clarity_noun", "clarity work")

    return (
        f"Congratulations — we’re ready to create your {clarity_noun}.\n\n"
        "Your content has been fully analysed, structured, refined, and packaged.\n"
        "Scroll down to explore your sections, insights, and final output."
    )
